image: gcc



stages:
  - compile_deps
  - build
  - test



fmt:
  stage: compile_deps
  script:
    - apt update;
      apt -y upgrade;
      apt -y install cmake
    - |
      if [[ ! -d ./fmt ]]; then
        git clone https://github.com/fmtlib/fmt.git ./fmt;
        cmake -S ./fmt -B ./fmt/build -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE;
        cmake --build ./fmt/build;
      fi
  cache:
    paths:
      - ./fmt
  artifacts:
    paths:
      - ./fmt
    expire_in: 1 week



spdlog:
  stage: compile_deps
  script:
    - apt update;
      apt -y upgrade;
      apt -y install cmake
    - |
      if [[ ! -d ./spdlog ]]; then
        git clone https://github.com/gabime/spdlog.git ./spdlog;
        cmake -S ./spdlog -B ./spdlog/build;
        cmake --build ./spdlog/build;
      fi
  cache:
    paths:
      - ./spdlog
  artifacts:
    paths:
      - ./spdlog
    expire_in: 1 week



catch2:
  stage: compile_deps
  script:
    - apt update;
      apt -y upgrade;
      apt -y install cmake
    - |
      if [[ ! -d ./catch2 ]]; then
        git clone https://github.com/catchorg/catch2.git ./catch2;
        cmake -S ./catch2 -B ./catch2/build;
        cmake --build ./catch2/build;
      fi
  cache:
    paths:
      - ./catch2
  artifacts:
    paths:
      - ./catch2
    expire_in: 1 week



build:
  stage: build
  before_script:
    - apt update;
      apt -y upgrade;
      apt -y install cmake libboost-program-options-dev
    - cmake --build ./fmt/build    --target install;
    - cmake --build ./spdlog/build --target install;
    - cmake --build ./catch2/build --target install;
  script:
    - cmake -S. -B./build && cmake --build ./build
  cache:
    paths:
      - ./build
  artifacts:
    paths:
      - ./build
    expire_in: 1 week



test:
  stage: test
  script:
    - ./build/aml_tests

