variables:
  IMAGE_TAG:        $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  IMAGE_TAG_LATEST: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:latest

stages:
  - build
  - test

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker pull $IMAGE_TAG_LATEST || true
    - docker build --cache-from $IMAGE_TAG_LATEST --tag $IMAGE_TAG .
    - docker tag  $IMAGE_TAG $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG

test:
  stage: test
  script:
    - docker pull $IMAGE_TAG
    - docker run --entrypoint aml_tests $IMAGE_TAG
